# Generated by Django 3.1.4 on 2020-12-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newreq', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Call',
        ),
    ]
